// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.bloombox.schema.product.struct.nano;

@SuppressWarnings("hiding")
public interface BaseStructs {

  // enum ProductFlag
  public static final int VISIBLE = 0;
  public static final int PREMIUM = 1;
  public static final int FEATURED = 2;
  public static final int LASTCHANCE = 3;
  public static final int INHOUSE = 4;
}
