// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.bloombox.schema.product.struct.nano;

@SuppressWarnings("hiding")
public interface MaterialSpecies {

  // enum Species
  public static final int UNSPECIFIED = 0;
  public static final int SATIVA = 1;
  public static final int HYBRID_SATIVA = 2;
  public static final int HYBRID = 3;
  public static final int HYBRID_INDICA = 4;
  public static final int INDICA = 5;
}
