// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.bloombox.schema.product.struct.nano;

@SuppressWarnings("hiding")
public final class PricingTierAvailability extends
    com.google.protobuf.nano.MessageNano {

  private static volatile PricingTierAvailability[] _emptyArray;
  public static PricingTierAvailability[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new PricingTierAvailability[0];
        }
      }
    }
    return _emptyArray;
  }

  // bool offered = 1;
  public boolean offered;

  // bool available = 2;
  public boolean available;

  public PricingTierAvailability() {
    clear();
  }

  public PricingTierAvailability clear() {
    offered = false;
    available = false;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.offered != false) {
      output.writeBool(1, this.offered);
    }
    if (this.available != false) {
      output.writeBool(2, this.available);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.offered != false) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeBoolSize(1, this.offered);
    }
    if (this.available != false) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeBoolSize(2, this.available);
    }
    return size;
  }

  @Override
  public PricingTierAvailability mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 8: {
          this.offered = input.readBool();
          break;
        }
        case 16: {
          this.available = input.readBool();
          break;
        }
      }
    }
  }

  public static PricingTierAvailability parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new PricingTierAvailability(), data);
  }

  public static PricingTierAvailability parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new PricingTierAvailability().mergeFrom(input);
  }
}
