// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.bloombox.schema.product.struct.nano;

@SuppressWarnings("hiding")
public final class ProductFlagValue extends
    com.google.protobuf.nano.MessageNano {

  private static volatile ProductFlagValue[] _emptyArray;
  public static ProductFlagValue[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new ProductFlagValue[0];
        }
      }
    }
    return _emptyArray;
  }

  // .ProductFlag type = 1;
  public int type;

  // bool value = 2;
  public boolean value;

  public ProductFlagValue() {
    clear();
  }

  public ProductFlagValue clear() {
    type = io.bloombox.schema.product.struct.nano.BaseStructs.VISIBLE;
    value = false;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.type != io.bloombox.schema.product.struct.nano.BaseStructs.VISIBLE) {
      output.writeInt32(1, this.type);
    }
    if (this.value != false) {
      output.writeBool(2, this.value);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.type != io.bloombox.schema.product.struct.nano.BaseStructs.VISIBLE) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeInt32Size(1, this.type);
    }
    if (this.value != false) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeBoolSize(2, this.value);
    }
    return size;
  }

  @Override
  public ProductFlagValue mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 8: {
          int value = input.readInt32();
          switch (value) {
            case io.bloombox.schema.product.struct.nano.BaseStructs.VISIBLE:
            case io.bloombox.schema.product.struct.nano.BaseStructs.PREMIUM:
            case io.bloombox.schema.product.struct.nano.BaseStructs.FEATURED:
            case io.bloombox.schema.product.struct.nano.BaseStructs.LASTCHANCE:
            case io.bloombox.schema.product.struct.nano.BaseStructs.INHOUSE:
              this.type = value;
              break;
          }
          break;
        }
        case 16: {
          this.value = input.readBool();
          break;
        }
      }
    }
  }

  public static ProductFlagValue parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new ProductFlagValue(), data);
  }

  public static ProductFlagValue parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new ProductFlagValue().mergeFrom(input);
  }
}
