# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structs/pricing/PricingDescriptor.proto

require 'google/protobuf'

require 'structs/pricing/SaleDescriptor_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "PricingTierAvailability" do
    optional :offered, :bool, 1
    optional :available, :bool, 2
  end
  add_message "UnitPricingDescriptor" do
    optional :price_value, :float, 1
    optional :status, :message, 2, "PricingTierAvailability"
    repeated :discounts, :message, 3, "SaleDescriptor"
  end
  add_message "WeightedPricingDescriptor" do
    optional :weight, :enum, 1, "PricingWeightTier"
    optional :tier, :message, 2, "UnitPricingDescriptor"
    optional :weightInGrams, :float, 3
  end
  add_message "FreebiePricingDescriptor" do
  end
  add_message "PricingDescriptor" do
    optional :type, :enum, 1, "PricingType"
    optional :unit, :message, 20, "UnitPricingDescriptor"
    optional :weighted, :message, 21, "WeightedPricingDescriptor"
    optional :freebie, :message, 22, "FreebiePricingDescriptor"
  end
  add_message "ProductPricing" do
    repeated :discounts, :message, 1, "SaleDescriptor"
    repeated :manifest, :message, 2, "PricingDescriptor"
  end
  add_enum "PricingType" do
    value :UNIT, 0
    value :WEIGHTED, 1
    value :FREEBIE, 2
  end
  add_enum "PricingWeightTier" do
    value :OTHER, 0
    value :GRAM, 1
    value :HALFGRAM, 2
    value :QUARTERGRAM, 3
    value :DUB, 4
    value :EIGHTH, 5
    value :QUARTER, 6
    value :HALF, 7
    value :OUNCE, 8
    value :POUND, 9
  end
end

PricingTierAvailability = Google::Protobuf::DescriptorPool.generated_pool.lookup("PricingTierAvailability").msgclass
UnitPricingDescriptor = Google::Protobuf::DescriptorPool.generated_pool.lookup("UnitPricingDescriptor").msgclass
WeightedPricingDescriptor = Google::Protobuf::DescriptorPool.generated_pool.lookup("WeightedPricingDescriptor").msgclass
FreebiePricingDescriptor = Google::Protobuf::DescriptorPool.generated_pool.lookup("FreebiePricingDescriptor").msgclass
PricingDescriptor = Google::Protobuf::DescriptorPool.generated_pool.lookup("PricingDescriptor").msgclass
ProductPricing = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProductPricing").msgclass
PricingType = Google::Protobuf::DescriptorPool.generated_pool.lookup("PricingType").enummodule
PricingWeightTier = Google::Protobuf::DescriptorPool.generated_pool.lookup("PricingWeightTier").enummodule
