<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: media/MediaKey.proto

namespace GPBMetadata\Media;

class MediaKey
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a670a146d656469612f4d656469614b65792e70726f746f22160a084d65" .
            "6469614b6579120a0a026964180120012809422f0a18696f2e626c6f6f6d" .
            "626f782e736368656d612e6d65646961420c4d656469614974656d4b6579" .
            "48015001f80101620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

