// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: structs/FlagsDescriptor.proto

package io.bloombox.schema.product.struct;

public interface FlagsDescriptorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FlagsDescriptor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool visible = 1;</code>
   */
  boolean getVisible();

  /**
   * <code>bool premium = 2;</code>
   */
  boolean getPremium();

  /**
   * <code>bool featured = 3;</code>
   */
  boolean getFeatured();

  /**
   * <code>bool lastchance = 4;</code>
   */
  boolean getLastchance();

  /**
   * <code>bool inhouse = 5;</code>
   */
  boolean getInhouse();
}
