// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: structs/pricing/SaleDescriptor.proto

package io.bloombox.schema.product.struct;

public final class ProductDiscount {
  private ProductDiscount() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaleDescriptor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaleDescriptor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$structs/pricing/SaleDescriptor.proto\"\307" +
      "\001\n\016SaleDescriptor\022\027\n\004type\030\001 \001(\0162\t.SaleTy" +
      "pe\022\021\n\teffective\030\002 \001(\004\022\022\n\nexpiration\030\003 \001(" +
      "\004\022\031\n\021percentage_amount\030\024 \001(\r\022\024\n\014bogo_tri" +
      "gger\030\025 \001(\r\022\023\n\013bogo_reward\030\026 \001(\r\022\027\n\017loyal" +
      "ty_trigger\030\027 \001(\r\022\026\n\016loyalty_reward\030\030 \001(\r" +
      "*1\n\010SaleType\022\016\n\nPERCENTAGE\020\000\022\010\n\004BOGO\020\001\022\013" +
      "\n\007LOYALTY\020\002B;\n!io.bloombox.schema.produc" +
      "t.structB\017ProductDiscountH\001P\001\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SaleDescriptor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SaleDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaleDescriptor_descriptor,
        new java.lang.String[] { "Type", "Effective", "Expiration", "PercentageAmount", "BogoTrigger", "BogoReward", "LoyaltyTrigger", "LoyaltyReward", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
