// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: structs/pricing/SaleDescriptor.proto

package io.bloombox.schema.product.struct;

public interface SaleDescriptorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaleDescriptor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * sale metadata
   * </pre>
   *
   * <code>.SaleType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <pre>
   * sale metadata
   * </pre>
   *
   * <code>.SaleType type = 1;</code>
   */
  io.bloombox.schema.product.struct.SaleType getType();

  /**
   * <code>uint64 effective = 2;</code>
   */
  long getEffective();

  /**
   * <code>uint64 expiration = 3;</code>
   */
  long getExpiration();

  /**
   * <pre>
   * sale amount and trigger properties
   * </pre>
   *
   * <code>uint32 percentage_amount = 20;</code>
   */
  int getPercentageAmount();

  /**
   * <code>uint32 bogo_trigger = 21;</code>
   */
  int getBogoTrigger();

  /**
   * <code>uint32 bogo_reward = 22;</code>
   */
  int getBogoReward();

  /**
   * <code>uint32 loyalty_trigger = 23;</code>
   */
  int getLoyaltyTrigger();

  /**
   * <code>uint32 loyalty_reward = 24;</code>
   */
  int getLoyaltyReward();
}
