// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: structs/pricing/SaleDescriptor.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from structs/pricing/SaleDescriptor.proto</summary>
public static partial class SaleDescriptorReflection {

  #region Descriptor
  /// <summary>File descriptor for structs/pricing/SaleDescriptor.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SaleDescriptorReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiRzdHJ1Y3RzL3ByaWNpbmcvU2FsZURlc2NyaXB0b3IucHJvdG8ixwEKDlNh",
          "bGVEZXNjcmlwdG9yEhcKBHR5cGUYASABKA4yCS5TYWxlVHlwZRIRCgllZmZl",
          "Y3RpdmUYAiABKAQSEgoKZXhwaXJhdGlvbhgDIAEoBBIZChFwZXJjZW50YWdl",
          "X2Ftb3VudBgUIAEoDRIUCgxib2dvX3RyaWdnZXIYFSABKA0SEwoLYm9nb19y",
          "ZXdhcmQYFiABKA0SFwoPbG95YWx0eV90cmlnZ2VyGBcgASgNEhYKDmxveWFs",
          "dHlfcmV3YXJkGBggASgNKjEKCFNhbGVUeXBlEg4KClBFUkNFTlRBR0UQABII",
          "CgRCT0dPEAESCwoHTE9ZQUxUWRACQjsKIWlvLmJsb29tYm94LnNjaGVtYS5w",
          "cm9kdWN0LnN0cnVjdEIPUHJvZHVjdERpc2NvdW50SAFQAfgBAWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SaleType), }, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SaleDescriptor), global::SaleDescriptor.Parser, new[]{ "Type", "Effective", "Expiration", "PercentageAmount", "BogoTrigger", "BogoReward", "LoyaltyTrigger", "LoyaltyReward" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum SaleType {
  [pbr::OriginalName("PERCENTAGE")] Percentage = 0,
  [pbr::OriginalName("BOGO")] Bogo = 1,
  [pbr::OriginalName("LOYALTY")] Loyalty = 2,
}

#endregion

#region Messages
public sealed partial class SaleDescriptor : pb::IMessage<SaleDescriptor> {
  private static readonly pb::MessageParser<SaleDescriptor> _parser = new pb::MessageParser<SaleDescriptor>(() => new SaleDescriptor());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SaleDescriptor> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SaleDescriptorReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SaleDescriptor() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SaleDescriptor(SaleDescriptor other) : this() {
    type_ = other.type_;
    effective_ = other.effective_;
    expiration_ = other.expiration_;
    percentageAmount_ = other.percentageAmount_;
    bogoTrigger_ = other.bogoTrigger_;
    bogoReward_ = other.bogoReward_;
    loyaltyTrigger_ = other.loyaltyTrigger_;
    loyaltyReward_ = other.loyaltyReward_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SaleDescriptor Clone() {
    return new SaleDescriptor(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::SaleType type_ = 0;
  /// <summary>
  /// sale metadata
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::SaleType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "effective" field.</summary>
  public const int EffectiveFieldNumber = 2;
  private ulong effective_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ulong Effective {
    get { return effective_; }
    set {
      effective_ = value;
    }
  }

  /// <summary>Field number for the "expiration" field.</summary>
  public const int ExpirationFieldNumber = 3;
  private ulong expiration_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ulong Expiration {
    get { return expiration_; }
    set {
      expiration_ = value;
    }
  }

  /// <summary>Field number for the "percentage_amount" field.</summary>
  public const int PercentageAmountFieldNumber = 20;
  private uint percentageAmount_;
  /// <summary>
  /// sale amount and trigger properties
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint PercentageAmount {
    get { return percentageAmount_; }
    set {
      percentageAmount_ = value;
    }
  }

  /// <summary>Field number for the "bogo_trigger" field.</summary>
  public const int BogoTriggerFieldNumber = 21;
  private uint bogoTrigger_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint BogoTrigger {
    get { return bogoTrigger_; }
    set {
      bogoTrigger_ = value;
    }
  }

  /// <summary>Field number for the "bogo_reward" field.</summary>
  public const int BogoRewardFieldNumber = 22;
  private uint bogoReward_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint BogoReward {
    get { return bogoReward_; }
    set {
      bogoReward_ = value;
    }
  }

  /// <summary>Field number for the "loyalty_trigger" field.</summary>
  public const int LoyaltyTriggerFieldNumber = 23;
  private uint loyaltyTrigger_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint LoyaltyTrigger {
    get { return loyaltyTrigger_; }
    set {
      loyaltyTrigger_ = value;
    }
  }

  /// <summary>Field number for the "loyalty_reward" field.</summary>
  public const int LoyaltyRewardFieldNumber = 24;
  private uint loyaltyReward_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint LoyaltyReward {
    get { return loyaltyReward_; }
    set {
      loyaltyReward_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SaleDescriptor);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SaleDescriptor other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (Effective != other.Effective) return false;
    if (Expiration != other.Expiration) return false;
    if (PercentageAmount != other.PercentageAmount) return false;
    if (BogoTrigger != other.BogoTrigger) return false;
    if (BogoReward != other.BogoReward) return false;
    if (LoyaltyTrigger != other.LoyaltyTrigger) return false;
    if (LoyaltyReward != other.LoyaltyReward) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != 0) hash ^= Type.GetHashCode();
    if (Effective != 0UL) hash ^= Effective.GetHashCode();
    if (Expiration != 0UL) hash ^= Expiration.GetHashCode();
    if (PercentageAmount != 0) hash ^= PercentageAmount.GetHashCode();
    if (BogoTrigger != 0) hash ^= BogoTrigger.GetHashCode();
    if (BogoReward != 0) hash ^= BogoReward.GetHashCode();
    if (LoyaltyTrigger != 0) hash ^= LoyaltyTrigger.GetHashCode();
    if (LoyaltyReward != 0) hash ^= LoyaltyReward.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Type != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Effective != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(Effective);
    }
    if (Expiration != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(Expiration);
    }
    if (PercentageAmount != 0) {
      output.WriteRawTag(160, 1);
      output.WriteUInt32(PercentageAmount);
    }
    if (BogoTrigger != 0) {
      output.WriteRawTag(168, 1);
      output.WriteUInt32(BogoTrigger);
    }
    if (BogoReward != 0) {
      output.WriteRawTag(176, 1);
      output.WriteUInt32(BogoReward);
    }
    if (LoyaltyTrigger != 0) {
      output.WriteRawTag(184, 1);
      output.WriteUInt32(LoyaltyTrigger);
    }
    if (LoyaltyReward != 0) {
      output.WriteRawTag(192, 1);
      output.WriteUInt32(LoyaltyReward);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Type != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (Effective != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Effective);
    }
    if (Expiration != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Expiration);
    }
    if (PercentageAmount != 0) {
      size += 2 + pb::CodedOutputStream.ComputeUInt32Size(PercentageAmount);
    }
    if (BogoTrigger != 0) {
      size += 2 + pb::CodedOutputStream.ComputeUInt32Size(BogoTrigger);
    }
    if (BogoReward != 0) {
      size += 2 + pb::CodedOutputStream.ComputeUInt32Size(BogoReward);
    }
    if (LoyaltyTrigger != 0) {
      size += 2 + pb::CodedOutputStream.ComputeUInt32Size(LoyaltyTrigger);
    }
    if (LoyaltyReward != 0) {
      size += 2 + pb::CodedOutputStream.ComputeUInt32Size(LoyaltyReward);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SaleDescriptor other) {
    if (other == null) {
      return;
    }
    if (other.Type != 0) {
      Type = other.Type;
    }
    if (other.Effective != 0UL) {
      Effective = other.Effective;
    }
    if (other.Expiration != 0UL) {
      Expiration = other.Expiration;
    }
    if (other.PercentageAmount != 0) {
      PercentageAmount = other.PercentageAmount;
    }
    if (other.BogoTrigger != 0) {
      BogoTrigger = other.BogoTrigger;
    }
    if (other.BogoReward != 0) {
      BogoReward = other.BogoReward;
    }
    if (other.LoyaltyTrigger != 0) {
      LoyaltyTrigger = other.LoyaltyTrigger;
    }
    if (other.LoyaltyReward != 0) {
      LoyaltyReward = other.LoyaltyReward;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          type_ = (global::SaleType) input.ReadEnum();
          break;
        }
        case 16: {
          Effective = input.ReadUInt64();
          break;
        }
        case 24: {
          Expiration = input.ReadUInt64();
          break;
        }
        case 160: {
          PercentageAmount = input.ReadUInt32();
          break;
        }
        case 168: {
          BogoTrigger = input.ReadUInt32();
          break;
        }
        case 176: {
          BogoReward = input.ReadUInt32();
          break;
        }
        case 184: {
          LoyaltyTrigger = input.ReadUInt32();
          break;
        }
        case 192: {
          LoyaltyReward = input.ReadUInt32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
