<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products/Flower.proto

namespace GPBMetadata\Products;

class Flower
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Base\ProductKey::initOnce();
        \GPBMetadata\Content\MaterialsData::initOnce();
        \GPBMetadata\Content\ProductContent::initOnce();
        \GPBMetadata\Structs\FlagsDescriptor::initOnce();
        \GPBMetadata\Structs\Pricing\PricingDescriptor::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8020a1570726f64756374732f466c6f7765722e70726f746f1a1b636f" .
            "6e74656e742f4d6174657269616c73446174612e70726f746f1a1c636f6e" .
            "74656e742f50726f64756374436f6e74656e742e70726f746f1a1d737472" .
            "756374732f466c61677344657363726970746f722e70726f746f1a277374" .
            "72756374732f70726963696e672f50726963696e6744657363726970746f" .
            "722e70726f746f22b3010a06466c6f77657212180a036b65791801200128" .
            "0b320b2e50726f647563744b657912250a0c70726f647563745f64617461" .
            "18142001280b320f2e50726f64756374436f6e74656e7412250a0d6d6174" .
            "657269616c5f6461746118152001280b320e2e4d6174657269616c734461" .
            "7461121f0a05666c61677318162001280b32102e466c6167734465736372" .
            "6970746f7212200a0770726963696e6718172001280b320f2e50726f6475" .
            "637450726963696e67421e0a1a696f2e626c6f6f6d626f782e736368656d" .
            "612e70726f647563745000620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

