// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base/Compression.proto

package io.bloombox.schema.base;

public interface CompressionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Compression)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool enabled = 1;</code>
   */
  boolean getEnabled();

  /**
   * <code>.Compression.Type type = 2;</code>
   */
  int getTypeValue();
  /**
   * <code>.Compression.Type type = 2;</code>
   */
  io.bloombox.schema.base.Compression.Type getType();
}
