// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base/ProductKind.proto

package io.bloombox.schema.base;

/**
 * Protobuf enum {@code ProductKind}
 */
public enum ProductKind
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FLOWERS = 0;</code>
   */
  FLOWERS(0),
  /**
   * <code>EDIBLES = 1;</code>
   */
  EDIBLES(1),
  /**
   * <code>EXTRACTS = 2;</code>
   */
  EXTRACTS(2),
  /**
   * <code>PREROLLS = 3;</code>
   */
  PREROLLS(3),
  /**
   * <code>APOTHECARY = 4;</code>
   */
  APOTHECARY(4),
  /**
   * <code>CARTRIDGES = 5;</code>
   */
  CARTRIDGES(5),
  /**
   * <code>PLANTS = 6;</code>
   */
  PLANTS(6),
  /**
   * <code>MERCHANDISE = 7;</code>
   */
  MERCHANDISE(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>FLOWERS = 0;</code>
   */
  public static final int FLOWERS_VALUE = 0;
  /**
   * <code>EDIBLES = 1;</code>
   */
  public static final int EDIBLES_VALUE = 1;
  /**
   * <code>EXTRACTS = 2;</code>
   */
  public static final int EXTRACTS_VALUE = 2;
  /**
   * <code>PREROLLS = 3;</code>
   */
  public static final int PREROLLS_VALUE = 3;
  /**
   * <code>APOTHECARY = 4;</code>
   */
  public static final int APOTHECARY_VALUE = 4;
  /**
   * <code>CARTRIDGES = 5;</code>
   */
  public static final int CARTRIDGES_VALUE = 5;
  /**
   * <code>PLANTS = 6;</code>
   */
  public static final int PLANTS_VALUE = 6;
  /**
   * <code>MERCHANDISE = 7;</code>
   */
  public static final int MERCHANDISE_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ProductKind valueOf(int value) {
    return forNumber(value);
  }

  public static ProductKind forNumber(int value) {
    switch (value) {
      case 0: return FLOWERS;
      case 1: return EDIBLES;
      case 2: return EXTRACTS;
      case 3: return PREROLLS;
      case 4: return APOTHECARY;
      case 5: return CARTRIDGES;
      case 6: return PLANTS;
      case 7: return MERCHANDISE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProductKind>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ProductKind> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ProductKind>() {
          public ProductKind findValueByNumber(int number) {
            return ProductKind.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.bloombox.schema.base.ProductKindOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ProductKind[] VALUES = values();

  public static ProductKind valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ProductKind(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ProductKind)
}

