// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package io.bloombox.schema.base;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ProductKey key = 1;</code>
   */
  boolean hasKey();
  /**
   * <code>.ProductKey key = 1;</code>
   */
  io.bloombox.schema.base.ProductKey getKey();
  /**
   * <code>.ProductKey key = 1;</code>
   */
  io.bloombox.schema.base.ProductKeyOrBuilder getKeyOrBuilder();

  /**
   * <code>.ProductType type = 2;</code>
   */
  boolean hasType();
  /**
   * <code>.ProductType type = 2;</code>
   */
  io.bloombox.schema.base.ProductType getType();
  /**
   * <code>.ProductType type = 2;</code>
   */
  io.bloombox.schema.base.ProductTypeOrBuilder getTypeOrBuilder();

  /**
   * <code>.google.protobuf.Any data = 3;</code>
   */
  boolean hasData();
  /**
   * <code>.google.protobuf.Any data = 3;</code>
   */
  com.google.protobuf.Any getData();
  /**
   * <code>.google.protobuf.Any data = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getDataOrBuilder();
}
