<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/ProductKind.proto

namespace GPBMetadata\Base;

class ProductKind
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad1010a16626173652f50726f647563744b696e642e70726f746f2a8001" .
            "0a0b50726f647563744b696e64120b0a07464c4f574552531000120b0a07" .
            "454449424c45531001120c0a0845585452414354531002120c0a08505245" .
            "524f4c4c531003120e0a0a41504f544845434152591004120e0a0a434152" .
            "545249444745531005120a0a06504c414e54531006120f0a0b4d45524348" .
            "414e444953451007422c0a17696f2e626c6f6f6d626f782e736368656d61" .
            "2e62617365420f4261736550726f647563744b696e645001620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

