<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/Product.proto

namespace GPBMetadata\Base;

class Product
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Base\ProductKey::initOnce();
        \GPBMetadata\Base\ProductType::initOnce();
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad1010a12626173652f50726f647563742e70726f746f1a16626173652f" .
            "50726f64756374547970652e70726f746f1a19676f6f676c652f70726f74" .
            "6f6275662f616e792e70726f746f22630a0750726f6475637412180a036b" .
            "657918012001280b320b2e50726f647563744b6579121a0a047479706518" .
            "022001280b320c2e50726f647563745479706512220a0464617461180320" .
            "01280b32142e676f6f676c652e70726f746f6275662e416e79421b0a1769" .
            "6f2e626c6f6f6d626f782e736368656d612e626173655001620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

