<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structs/Grow.proto

namespace GPBMetadata\Structs;

class Grow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a81010a12737472756374732f47726f772e70726f746f2a3c0a0447726f" .
            "77120b0a0747454e455249431000120a0a06494e444f4f521001120e0a0a" .
            "475245454e484f5553451002120b0a074f5554444f4f52100342250a2169" .
            "6f2e626c6f6f6d626f782e736368656d612e70726f647563742e73747275" .
            "63745001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

