<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structs/pricing/SaleDescriptor.proto

namespace GPBMetadata\Structs\Pricing;

class SaleDescriptor
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae8020a24737472756374732f70726963696e672f53616c654465736372" .
            "6970746f722e70726f746f22c7010a0e53616c6544657363726970746f72" .
            "12170a047479706518012001280e32092e53616c655479706512110a0965" .
            "666665637469766518022001280412120a0a65787069726174696f6e1803" .
            "2001280412190a1170657263656e746167655f616d6f756e741814200128" .
            "0d12140a0c626f676f5f7472696767657218152001280d12130a0b626f67" .
            "6f5f72657761726418162001280d12170a0f6c6f79616c74795f74726967" .
            "67657218172001280d12160a0e6c6f79616c74795f726577617264181820" .
            "01280d2a310a0853616c6554797065120e0a0a50455243454e5441474510" .
            "0012080a04424f474f1001120b0a074c4f59414c54591002423b0a21696f" .
            "2e626c6f6f6d626f782e736368656d612e70726f647563742e7374727563" .
            "74420f50726f64756374446973636f756e7448015001f80101620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

