<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content/Brand.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Brand</code>
 */
class Brand extends \Google\Protobuf\Internal\Message
{
    /**
     * -- Basic Properties
     *
     * Generated from protobuf field <code>.Name name = 1;</code>
     */
    private $name = null;
    /**
     * Generated from protobuf field <code>.Brand parent = 2;</code>
     */
    private $parent = null;
    /**
     * Generated from protobuf field <code>.Content summary = 3;</code>
     */
    private $summary = null;
    /**
     * -- Media
     *
     * Generated from protobuf field <code>repeated .MediaItem media = 20;</code>
     */
    private $media;

    public function __construct() {
        \GPBMetadata\Content\Brand::initOnce();
        parent::__construct();
    }

    /**
     * -- Basic Properties
     *
     * Generated from protobuf field <code>.Name name = 1;</code>
     * @return \Name
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * -- Basic Properties
     *
     * Generated from protobuf field <code>.Name name = 1;</code>
     * @param \Name $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkMessage($var, \Name::class);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Brand parent = 2;</code>
     * @return \Brand
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Generated from protobuf field <code>.Brand parent = 2;</code>
     * @param \Brand $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkMessage($var, \Brand::class);
        $this->parent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Content summary = 3;</code>
     * @return \Content
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Generated from protobuf field <code>.Content summary = 3;</code>
     * @param \Content $var
     * @return $this
     */
    public function setSummary($var)
    {
        GPBUtil::checkMessage($var, \Content::class);
        $this->summary = $var;

        return $this;
    }

    /**
     * -- Media
     *
     * Generated from protobuf field <code>repeated .MediaItem media = 20;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMedia()
    {
        return $this->media;
    }

    /**
     * -- Media
     *
     * Generated from protobuf field <code>repeated .MediaItem media = 20;</code>
     * @param \MediaItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMedia($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \MediaItem::class);
        $this->media = $arr;

        return $this;
    }

}

