<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/Compression.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Compression</code>
 */
class Compression extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bool enabled = 1;</code>
     */
    private $enabled = false;
    /**
     * <code>.Compression.Type type = 2;</code>
     */
    private $type = 0;

    public function __construct() {
        \GPBMetadata\Base\Compression::initOnce();
        parent::__construct();
    }

    /**
     * <code>bool enabled = 1;</code>
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * <code>bool enabled = 1;</code>
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;
    }

    /**
     * <code>.Compression.Type type = 2;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <code>.Compression.Type type = 2;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Compression_Type::class);
        $this->type = $var;
    }

}

