<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content/Content.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Content</code>
 */
class Content extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.Content.Type type = 1;</code>
     */
    private $type = 0;
    /**
     * <code>.Content.Encoding encoding = 2;</code>
     */
    private $encoding = 0;
    /**
     * <code>bytes content = 3;</code>
     */
    private $content = '';
    /**
     * <code>.Language language = 4;</code>
     */
    private $language = 0;
    /**
     * <code>.Compression compression = 5;</code>
     */
    private $compression = null;

    public function __construct() {
        \GPBMetadata\Content\Content::initOnce();
        parent::__construct();
    }

    /**
     * <code>.Content.Type type = 1;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <code>.Content.Type type = 1;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Content_Type::class);
        $this->type = $var;
    }

    /**
     * <code>.Content.Encoding encoding = 2;</code>
     */
    public function getEncoding()
    {
        return $this->encoding;
    }

    /**
     * <code>.Content.Encoding encoding = 2;</code>
     */
    public function setEncoding($var)
    {
        GPBUtil::checkEnum($var, \Content_Encoding::class);
        $this->encoding = $var;
    }

    /**
     * <code>bytes content = 3;</code>
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * <code>bytes content = 3;</code>
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->content = $var;
    }

    /**
     * <code>.Language language = 4;</code>
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * <code>.Language language = 4;</code>
     */
    public function setLanguage($var)
    {
        GPBUtil::checkEnum($var, \Language::class);
        $this->language = $var;
    }

    /**
     * <code>.Compression compression = 5;</code>
     */
    public function getCompression()
    {
        return $this->compression;
    }

    /**
     * <code>.Compression compression = 5;</code>
     */
    public function setCompression(&$var)
    {
        GPBUtil::checkMessage($var, \Compression::class);
        $this->compression = $var;
    }

}

