<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content/Content.proto

/**
 * Protobuf enum <code>Content.Type</code>
 */
class Content_Type
{
    /**
     * <code>TEXT = 0;</code>
     */
    const TEXT = 0;
    /**
     * <code>MARKDOWN = 1;</code>
     */
    const MARKDOWN = 1;
    /**
     * <code>HTML = 2;</code>
     */
    const HTML = 2;
}

