<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structs/Genetics.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Genetics</code>
 */
class Genetics extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Name male = 1;</code>
     */
    private $male = null;
    /**
     * Generated from protobuf field <code>.Name female = 2;</code>
     */
    private $female = null;

    public function __construct() {
        \GPBMetadata\Structs\Genetics::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.Name male = 1;</code>
     * @return \Name
     */
    public function getMale()
    {
        return $this->male;
    }

    /**
     * Generated from protobuf field <code>.Name male = 1;</code>
     * @param \Name $var
     * @return $this
     */
    public function setMale($var)
    {
        GPBUtil::checkMessage($var, \Name::class);
        $this->male = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Name female = 2;</code>
     * @return \Name
     */
    public function getFemale()
    {
        return $this->female;
    }

    /**
     * Generated from protobuf field <code>.Name female = 2;</code>
     * @param \Name $var
     * @return $this
     */
    public function setFemale($var)
    {
        GPBUtil::checkMessage($var, \Name::class);
        $this->female = $var;

        return $this;
    }

}

