<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content/MaterialsData.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MaterialsData</code>
 */
class MaterialsData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string ingredients = 1;</code>
     */
    private $ingredients;
    /**
     * Generated from protobuf field <code>.Grow grow = 2;</code>
     */
    private $grow = 0;
    /**
     * Generated from protobuf field <code>.Species species = 3;</code>
     */
    private $species = 0;
    /**
     * Generated from protobuf field <code>.Genetics genetics = 4;</code>
     */
    private $genetics = null;

    public function __construct() {
        \GPBMetadata\Content\MaterialsData::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated string ingredients = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIngredients()
    {
        return $this->ingredients;
    }

    /**
     * Generated from protobuf field <code>repeated string ingredients = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIngredients($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ingredients = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Grow grow = 2;</code>
     * @return int
     */
    public function getGrow()
    {
        return $this->grow;
    }

    /**
     * Generated from protobuf field <code>.Grow grow = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGrow($var)
    {
        GPBUtil::checkEnum($var, \Grow::class);
        $this->grow = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Species species = 3;</code>
     * @return int
     */
    public function getSpecies()
    {
        return $this->species;
    }

    /**
     * Generated from protobuf field <code>.Species species = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSpecies($var)
    {
        GPBUtil::checkEnum($var, \Species::class);
        $this->species = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Genetics genetics = 4;</code>
     * @return \Genetics
     */
    public function getGenetics()
    {
        return $this->genetics;
    }

    /**
     * Generated from protobuf field <code>.Genetics genetics = 4;</code>
     * @param \Genetics $var
     * @return $this
     */
    public function setGenetics($var)
    {
        GPBUtil::checkMessage($var, \Genetics::class);
        $this->genetics = $var;

        return $this;
    }

}

