<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content/Name.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Name</code>
 */
class Name extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * basic name
     * </pre>
     *
     * <code>string primary = 1;</code>
     */
    private $primary = '';
    /**
     * <pre>
     * display name
     * </pre>
     *
     * <code>string display = 2;</code>
     */
    private $display = '';

    public function __construct() {
        \GPBMetadata\Content\Name::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * basic name
     * </pre>
     *
     * <code>string primary = 1;</code>
     */
    public function getPrimary()
    {
        return $this->primary;
    }

    /**
     * <pre>
     * basic name
     * </pre>
     *
     * <code>string primary = 1;</code>
     */
    public function setPrimary($var)
    {
        GPBUtil::checkString($var, True);
        $this->primary = $var;
    }

    /**
     * <pre>
     * display name
     * </pre>
     *
     * <code>string display = 2;</code>
     */
    public function getDisplay()
    {
        return $this->display;
    }

    /**
     * <pre>
     * display name
     * </pre>
     *
     * <code>string display = 2;</code>
     */
    public function setDisplay($var)
    {
        GPBUtil::checkString($var, True);
        $this->display = $var;
    }

}

