<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structs/pricing/PricingDescriptor.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * -- Pricing: Main Descriptor
 *
 * Generated from protobuf message <code>PricingDescriptor</code>
 */
class PricingDescriptor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.PricingType type = 1;</code>
     */
    private $type = 0;
    /**
     * -- descriptors
     *
     * Generated from protobuf field <code>.UnitPricingDescriptor unit = 20;</code>
     */
    private $unit = null;
    /**
     * Generated from protobuf field <code>.WeightedPricingDescriptor weighted = 21;</code>
     */
    private $weighted = null;
    /**
     * Generated from protobuf field <code>.FreebiePricingDescriptor freebie = 22;</code>
     */
    private $freebie = null;

    public function __construct() {
        \GPBMetadata\Structs\Pricing\PricingDescriptor::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.PricingType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.PricingType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \PricingType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * -- descriptors
     *
     * Generated from protobuf field <code>.UnitPricingDescriptor unit = 20;</code>
     * @return \UnitPricingDescriptor
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * -- descriptors
     *
     * Generated from protobuf field <code>.UnitPricingDescriptor unit = 20;</code>
     * @param \UnitPricingDescriptor $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkMessage($var, \UnitPricingDescriptor::class);
        $this->unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.WeightedPricingDescriptor weighted = 21;</code>
     * @return \WeightedPricingDescriptor
     */
    public function getWeighted()
    {
        return $this->weighted;
    }

    /**
     * Generated from protobuf field <code>.WeightedPricingDescriptor weighted = 21;</code>
     * @param \WeightedPricingDescriptor $var
     * @return $this
     */
    public function setWeighted($var)
    {
        GPBUtil::checkMessage($var, \WeightedPricingDescriptor::class);
        $this->weighted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.FreebiePricingDescriptor freebie = 22;</code>
     * @return \FreebiePricingDescriptor
     */
    public function getFreebie()
    {
        return $this->freebie;
    }

    /**
     * Generated from protobuf field <code>.FreebiePricingDescriptor freebie = 22;</code>
     * @param \FreebiePricingDescriptor $var
     * @return $this
     */
    public function setFreebie($var)
    {
        GPBUtil::checkMessage($var, \FreebiePricingDescriptor::class);
        $this->freebie = $var;

        return $this;
    }

}

