<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/ProductType.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * -- Product Type: Top-level -- //
 *
 * Generated from protobuf message <code>ProductType</code>
 */
class ProductType extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProductKind kind = 1;</code>
     */
    private $kind = 0;

    public function __construct() {
        \GPBMetadata\Base\ProductType::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.ProductKind kind = 1;</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.ProductKind kind = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \ProductKind::class);
        $this->kind = $var;

        return $this;
    }

}

