<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structs/Species.proto

/**
 * Protobuf enum <code>Species</code>
 */
class Species
{
    /**
     * <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * <code>SATIVA = 1;</code>
     */
    const SATIVA = 1;
    /**
     * <code>HYBRID_SATIVA = 2;</code>
     */
    const HYBRID_SATIVA = 2;
    /**
     * <code>HYBRID = 3;</code>
     */
    const HYBRID = 3;
    /**
     * <code>HYBRID_INDICA = 4;</code>
     */
    const HYBRID_INDICA = 4;
    /**
     * <code>INDICA = 5;</code>
     */
    const INDICA = 5;
}

