<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structs/pricing/PricingDescriptor.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>WeightedPricingDescriptor</code>
 */
class WeightedPricingDescriptor extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.PricingWeightTier weight = 1;</code>
     */
    private $weight = 0;
    /**
     * <code>.UnitPricingDescriptor tier = 2;</code>
     */
    private $tier = null;
    /**
     * <code>float weightInGrams = 3;</code>
     */
    private $weightInGrams = 0.0;

    public function __construct() {
        \GPBMetadata\Structs\Pricing\PricingDescriptor::initOnce();
        parent::__construct();
    }

    /**
     * <code>.PricingWeightTier weight = 1;</code>
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * <code>.PricingWeightTier weight = 1;</code>
     */
    public function setWeight($var)
    {
        GPBUtil::checkEnum($var, \PricingWeightTier::class);
        $this->weight = $var;
    }

    /**
     * <code>.UnitPricingDescriptor tier = 2;</code>
     */
    public function getTier()
    {
        return $this->tier;
    }

    /**
     * <code>.UnitPricingDescriptor tier = 2;</code>
     */
    public function setTier(&$var)
    {
        GPBUtil::checkMessage($var, \UnitPricingDescriptor::class);
        $this->tier = $var;
    }

    /**
     * <code>float weightInGrams = 3;</code>
     */
    public function getWeightInGrams()
    {
        return $this->weightInGrams;
    }

    /**
     * <code>float weightInGrams = 3;</code>
     */
    public function setWeightInGrams($var)
    {
        GPBUtil::checkFloat($var);
        $this->weightInGrams = $var;
    }

}

