// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Product.proto

/*
Package schema is a generated protocol buffer package.

It is generated from these files:
	Product.proto
	base/Compression.proto
	base/Language.proto
	base/ProductKey.proto
	base/ProductKind.proto
	base/ProductType.proto
	content/Brand.proto
	content/Content.proto
	content/MaterialsData.proto
	content/Name.proto
	content/ProductContent.proto
	media/MediaItem.proto
	media/MediaKey.proto
	media/MediaType.proto
	products/Flower.proto
	structs/FlagsDescriptor.proto
	structs/Genetics.proto
	structs/Grow.proto
	structs/Species.proto
	structs/pricing/PricingDescriptor.proto
	structs/pricing/SaleDescriptor.proto

It has these top-level messages:
	Product
	Compression
	ProductKey
	ProductType
	Brand
	Content
	MaterialsData
	Name
	ProductContent
	MediaItem
	MediaKey
	MediaType
	ImageType
	DocumentType
	VideoType
	Flower
	ProductFlagValue
	ProductFlagset
	FlagsDescriptor
	Genetics
	PricingTierAvailability
	UnitPricingDescriptor
	WeightedPricingDescriptor
	FreebiePricingDescriptor
	PricingDescriptor
	ProductPricing
	SaleDescriptor
*/
package schema

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// -- Product Type: Top-level -- //
type Product struct {
	Key  *ProductKey          `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Type *ProductType         `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Data *google_protobuf.Any `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Product) GetKey() *ProductKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Product) GetType() *ProductType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Product) GetData() *google_protobuf.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "Product")
}

func init() { proto.RegisterFile("Product.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0d, 0x28, 0xca, 0x4f,
	0x29, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x12, 0x4d, 0x4a, 0x2c, 0x4e, 0xd5,
	0x87, 0x8a, 0x79, 0xa7, 0x56, 0x42, 0x85, 0xc5, 0x90, 0x85, 0x43, 0x2a, 0x0b, 0x52, 0xa1, 0xe2,
	0x92, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x5e, 0x52, 0x69, 0x9a, 0x7e, 0x62, 0x1e,
	0x54, 0x8b, 0x52, 0x09, 0x17, 0x3b, 0x54, 0xbd, 0x90, 0x2c, 0x17, 0x73, 0x76, 0x6a, 0xa5, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x11, 0xb7, 0x1e, 0xc2, 0xf4, 0x20, 0x90, 0xb8, 0x90, 0x02, 0x17,
	0x4b, 0x49, 0x65, 0x41, 0xaa, 0x04, 0x13, 0x58, 0x9e, 0x47, 0x0f, 0xc9, 0x9a, 0x20, 0xb0, 0x8c,
	0x90, 0x06, 0x17, 0x4b, 0x4a, 0x62, 0x49, 0xa2, 0x04, 0x33, 0x58, 0x85, 0x88, 0x1e, 0xc4, 0x56,
	0x3d, 0x98, 0xad, 0x7a, 0x8e, 0x79, 0x95, 0x41, 0x60, 0x15, 0x4e, 0xba, 0x5c, 0xe2, 0x99, 0xf9,
	0x7a, 0x49, 0x39, 0xf9, 0xf9, 0xb9, 0x49, 0xf9, 0x15, 0x7a, 0xc5, 0xc9, 0x19, 0xa9, 0xb9, 0x89,
	0x7a, 0x20, 0xd7, 0x3b, 0x71, 0x3b, 0x25, 0x16, 0xa7, 0x42, 0xcd, 0xf6, 0x60, 0x0c, 0x60, 0xfc,
	0xc1, 0xc8, 0x98, 0xc4, 0x06, 0x36, 0xc2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x07, 0x9e,
	0xcf, 0x06, 0x01, 0x00, 0x00,
}
