// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.bloombox.schema.base.nano;

@SuppressWarnings("hiding")
public interface BaseLanguage {

  // enum Language
  public static final int ENGLISH = 0;
  public static final int SPANISH = 1;
  public static final int FRENCH = 2;
}
