// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: content/Brand.proto

package io.bloombox.schema.content;

public interface BrandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Brand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * -- Basic Properties
   * </pre>
   *
   * <code>.Name name = 1;</code>
   */
  boolean hasName();
  /**
   * <pre>
   * -- Basic Properties
   * </pre>
   *
   * <code>.Name name = 1;</code>
   */
  io.bloombox.schema.content.Name getName();
  /**
   * <pre>
   * -- Basic Properties
   * </pre>
   *
   * <code>.Name name = 1;</code>
   */
  io.bloombox.schema.content.NameOrBuilder getNameOrBuilder();

  /**
   * <code>.Brand parent = 2;</code>
   */
  boolean hasParent();
  /**
   * <code>.Brand parent = 2;</code>
   */
  io.bloombox.schema.content.Brand getParent();
  /**
   * <code>.Brand parent = 2;</code>
   */
  io.bloombox.schema.content.BrandOrBuilder getParentOrBuilder();

  /**
   * <code>.Content summary = 3;</code>
   */
  boolean hasSummary();
  /**
   * <code>.Content summary = 3;</code>
   */
  io.bloombox.schema.content.Content getSummary();
  /**
   * <code>.Content summary = 3;</code>
   */
  io.bloombox.schema.content.ContentOrBuilder getSummaryOrBuilder();

  /**
   * <pre>
   * -- Media
   * </pre>
   *
   * <code>repeated .MediaItem media = 20;</code>
   */
  java.util.List<io.bloombox.schema.media.MediaItem> 
      getMediaList();
  /**
   * <pre>
   * -- Media
   * </pre>
   *
   * <code>repeated .MediaItem media = 20;</code>
   */
  io.bloombox.schema.media.MediaItem getMedia(int index);
  /**
   * <pre>
   * -- Media
   * </pre>
   *
   * <code>repeated .MediaItem media = 20;</code>
   */
  int getMediaCount();
  /**
   * <pre>
   * -- Media
   * </pre>
   *
   * <code>repeated .MediaItem media = 20;</code>
   */
  java.util.List<? extends io.bloombox.schema.media.MediaItemOrBuilder> 
      getMediaOrBuilderList();
  /**
   * <pre>
   * -- Media
   * </pre>
   *
   * <code>repeated .MediaItem media = 20;</code>
   */
  io.bloombox.schema.media.MediaItemOrBuilder getMediaOrBuilder(
      int index);
}
