// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: content/ProductContent.proto

package io.bloombox.schema.content;

public interface ProductContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * -- Basic Properties
   * </pre>
   *
   * <code>.Name name = 1;</code>
   */
  boolean hasName();
  /**
   * <pre>
   * -- Basic Properties
   * </pre>
   *
   * <code>.Name name = 1;</code>
   */
  io.bloombox.schema.content.Name getName();
  /**
   * <pre>
   * -- Basic Properties
   * </pre>
   *
   * <code>.Name name = 1;</code>
   */
  io.bloombox.schema.content.NameOrBuilder getNameOrBuilder();

  /**
   * <pre>
   * narrative summary
   * </pre>
   *
   * <code>.Content summary = 2;</code>
   */
  boolean hasSummary();
  /**
   * <pre>
   * narrative summary
   * </pre>
   *
   * <code>.Content summary = 2;</code>
   */
  io.bloombox.schema.content.Content getSummary();
  /**
   * <pre>
   * narrative summary
   * </pre>
   *
   * <code>.Content summary = 2;</code>
   */
  io.bloombox.schema.content.ContentOrBuilder getSummaryOrBuilder();

  /**
   * <pre>
   * product's brand
   * </pre>
   *
   * <code>.Brand brand = 3;</code>
   */
  boolean hasBrand();
  /**
   * <pre>
   * product's brand
   * </pre>
   *
   * <code>.Brand brand = 3;</code>
   */
  io.bloombox.schema.content.Brand getBrand();
  /**
   * <pre>
   * product's brand
   * </pre>
   *
   * <code>.Brand brand = 3;</code>
   */
  io.bloombox.schema.content.BrandOrBuilder getBrandOrBuilder();

  /**
   * <pre>
   * -- Media
   * </pre>
   *
   * <code>repeated .MediaItem media = 20;</code>
   */
  java.util.List<io.bloombox.schema.media.MediaItem> 
      getMediaList();
  /**
   * <pre>
   * -- Media
   * </pre>
   *
   * <code>repeated .MediaItem media = 20;</code>
   */
  io.bloombox.schema.media.MediaItem getMedia(int index);
  /**
   * <pre>
   * -- Media
   * </pre>
   *
   * <code>repeated .MediaItem media = 20;</code>
   */
  int getMediaCount();
  /**
   * <pre>
   * -- Media
   * </pre>
   *
   * <code>repeated .MediaItem media = 20;</code>
   */
  java.util.List<? extends io.bloombox.schema.media.MediaItemOrBuilder> 
      getMediaOrBuilderList();
  /**
   * <pre>
   * -- Media
   * </pre>
   *
   * <code>repeated .MediaItem media = 20;</code>
   */
  io.bloombox.schema.media.MediaItemOrBuilder getMediaOrBuilder(
      int index);

  /**
   * <pre>
   * -- Extended Attributes
   * </pre>
   *
   * <code>.Content usage = 30;</code>
   */
  boolean hasUsage();
  /**
   * <pre>
   * -- Extended Attributes
   * </pre>
   *
   * <code>.Content usage = 30;</code>
   */
  io.bloombox.schema.content.Content getUsage();
  /**
   * <pre>
   * -- Extended Attributes
   * </pre>
   *
   * <code>.Content usage = 30;</code>
   */
  io.bloombox.schema.content.ContentOrBuilder getUsageOrBuilder();

  /**
   * <pre>
   * dosage advice
   * </pre>
   *
   * <code>.Content dosage = 31;</code>
   */
  boolean hasDosage();
  /**
   * <pre>
   * dosage advice
   * </pre>
   *
   * <code>.Content dosage = 31;</code>
   */
  io.bloombox.schema.content.Content getDosage();
  /**
   * <pre>
   * dosage advice
   * </pre>
   *
   * <code>.Content dosage = 31;</code>
   */
  io.bloombox.schema.content.ContentOrBuilder getDosageOrBuilder();

  /**
   * <pre>
   * internal advice
   * </pre>
   *
   * <code>.Content advice = 32;</code>
   */
  boolean hasAdvice();
  /**
   * <pre>
   * internal advice
   * </pre>
   *
   * <code>.Content advice = 32;</code>
   */
  io.bloombox.schema.content.Content getAdvice();
  /**
   * <pre>
   * internal advice
   * </pre>
   *
   * <code>.Content advice = 32;</code>
   */
  io.bloombox.schema.content.ContentOrBuilder getAdviceOrBuilder();
}
