<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content/Brand.proto

namespace GPBMetadata\Content;

class Brand
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Content\Name::initOnce();
        \GPBMetadata\Content\Content::initOnce();
        \GPBMetadata\Media\MediaItem::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae5010a13636f6e74656e742f4272616e642e70726f746f1a15636f6e74" .
            "656e742f436f6e74656e742e70726f746f1a156d656469612f4d65646961" .
            "4974656d2e70726f746f226a0a054272616e6412130a046e616d65180120" .
            "01280b32052e4e616d6512160a06706172656e7418022001280b32062e42" .
            "72616e6412190a0773756d6d61727918032001280b32082e436f6e74656e" .
            "7412190a056d6564696118142003280b320a2e4d656469614974656d422c" .
            "0a1a696f2e626c6f6f6d626f782e736368656d612e636f6e74656e74420c" .
            "4272616e64436f6e74656e745001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

